import { describe, expect, it } from 'vitest'
import { computeSignatureHashes, normalizeHeavy, normalizeLight, sha256 } from './hashing.js'

describe('byte-compatibility with v1 spam-signatures hashing', () => {
  it('sha256 is truncated to 32 hex chars like v1', () => {
    expect(sha256('test')).toBe('9f86d081884c7d659a2feaa0c55ad015')
    expect(sha256('test')).toHaveLength(32)
  })

  it('normalizeLight lowercases and collapses whitespace', () => {
    expect(normalizeLight('  ПрИвіТ   Світ \n ')).toBe('привіт світ')
  })

  it('normalizeHeavy templates mentions, urls, numbers, currency (v1 ground truth)', () => {
    // Expected string generated by running v1 helpers/spam-signatures.js
    expect(normalizeHeavy('Пиши @manager_777 на https://scam.example або t.me/abc за 500$'))
      .toBe('пиши @_ на _URL_ або _URL_ за _NUM__CUR_')
  })

  it('emoji-only text produces NO normalized hash (collision guard)', () => {
    const hashes = computeSignatureHashes('😀😀😀')
    expect(hashes).not.toBeNull()
    expect(hashes?.normalizedHash).toBeNull()
  })

  it('empty text produces null', () => {
    expect(computeSignatureHashes('')).toBeNull()
    expect(computeSignatureHashes('   ')).toBeNull()
  })

  it('same template with different numbers shares normalizedHash', () => {
    const a = computeSignatureHashes('Заробіток 500$ в день пиши @user1')!
    const b = computeSignatureHashes('Заробіток 9000$ в день пиши @user2')!
    expect(a.normalizedHash).toBe(b.normalizedHash)
    expect(a.exactHash).not.toBe(b.exactHash)
  })
})
