import { describe, expect, it } from 'vitest'
import {
  computeSignatureHashes, foldConfusables, normalizeHeavy, normalizeLight, sha256
} from './hashing.js'

describe('byte-compatibility with v1 spam-signatures hashing', () => {
  it('sha256 is truncated to 32 hex chars like v1', () => {
    expect(sha256('test')).toBe('9f86d081884c7d659a2feaa0c55ad015')
    expect(sha256('test')).toHaveLength(32)
  })

  it('normalizeLight lowercases and collapses whitespace', () => {
    expect(normalizeLight('  ПрИвіТ   Світ \n ')).toBe('привіт світ')
  })

  it('normalizeHeavy templates mentions, urls, numbers, currency (v1 ground truth)', () => {
    // Expected string generated by running v1 helpers/spam-signatures.js
    expect(normalizeHeavy('Пиши @manager_777 на https://scam.example або t.me/abc за 500$'))
      .toBe('пиши @_ на _URL_ або _URL_ за _NUM__CUR_')
  })

  it('emoji-only text produces NO normalized hash (collision guard)', () => {
    const hashes = computeSignatureHashes('😀😀😀')
    expect(hashes).not.toBeNull()
    expect(hashes?.normalizedHash).toBeNull()
  })

  it('empty text produces null', () => {
    expect(computeSignatureHashes('')).toBeNull()
    expect(computeSignatureHashes('   ')).toBeNull()
  })

  it('same template with different numbers shares normalizedHash', () => {
    const a = computeSignatureHashes('Заробіток 500$ в день пиши @user1')!
    const b = computeSignatureHashes('Заробіток 9000$ в день пиши @user2')!
    expect(a.normalizedHash).toBe(b.normalizedHash)
    expect(a.exactHash).not.toBe(b.exactHash)
  })
})

describe('foldConfusables', () => {
  // The rotation seen in production 2026-07-31: one advert reposted seven times,
  // each with a different Latin/Greek stand-in for a Cyrillic letter. Nothing
  // matched any of them, so the model was paid to read the same text seven times.
  const rotations = [
    'Ищу онлайн менеджера. От 50$ в день. Пиши в лс',
    'Ищу онлайη меhеджερа. От 50$ b деhь. Пиши b лс'
  ]

  it('collapses a homoglyph rotation to one string', () => {
    const folded = new Set(rotations.map((t) => foldConfusables(normalizeLight(t))))
    expect(folded.size).toBe(1)
  })

  it('is idempotent — folding a folded string changes nothing', () => {
    for (const text of rotations) {
      const once = foldConfusables(text)
      expect(foldConfusables(once)).toBe(once)
    }
  })

  /**
   * The same sender, the same chat, five minutes apart (production 2026-07-31
   * 11:06 → 11:12). The first sighting matched a signature; the rotation did
   * not, and the model was paid to read it again. Two gaps did it:
   *
   *  - a DIGIT standing in for a letter (`4` for `ч`), which the fold skipped
   *    on the grounds that folding digits "rewrites every price";
   *  - `λ` for `л`, which no class could express, because every class folded to
   *    a LATIN representative and these two letters have no Latin lookalike.
   */
  const digitAndLambdaRotation = [
    'Hужен менеджeр в чат, оплата от $50 — детали b ЛC.',
    'Нужен мeнеджеp в 4ат, оплαта от $50 — дεтали в ΛϹ.'
  ]

  it('collapses a rotation that used a digit and a lambda', () => {
    const folded = new Set(digitAndLambdaRotation.map((t) => foldConfusables(normalizeLight(t))))
    expect(folded.size).toBe(1)
  })

  it('folding digits cannot merge two different numbers', () => {
    // This is why the old objection ("it rewrites every price") did not hold:
    // distortion is harmless when both sides get it, and since distinct digits
    // fold to distinct letters, two different numbers stay different. Only
    // digit-for-letter evasion collapses, which is the entire point.
    expect(foldConfusables('2500')).not.toBe(foldConfusables('2600'))
    expect(foldConfusables('від 40 000 грн')).not.toBe(foldConfusables('від 50 000 грн'))
    expect(foldConfusables('4')).toBe(foldConfusables('ч'))
  })

  it('keeps distinct messages distinct', () => {
    const a = foldConfusables(normalizeLight('Доброго дня, підкажіть де можна відновити довідку'))
    const b = foldConfusables(normalizeLight('Шукаємо комплектувальника на склад, зарплата висока'))
    expect(a).not.toBe(b)
  })

  it('never grows the string — one codepoint folds to one', () => {
    for (const text of [...rotations, 'звичайний український текст без підмін']) {
      expect([...foldConfusables(text)].length).toBe([...text].length)
    }
  })
})

describe('computeSignatureHashes — folded layer', () => {
  it('gives homoglyph rotations the same foldedHash but different exactHash', () => {
    const a = computeSignatureHashes('Ищу онлайн менеджера. От 50$ в день. Пиши в лс')
    const b = computeSignatureHashes('Ищу онлайη меhеджερа. От 50$ b деhь. Пиши b лс')
    expect(a?.exactHash).not.toBe(b?.exactHash)
    expect(a?.foldedHash).not.toBe(null)
    expect(a?.foldedHash).toBe(b?.foldedHash)
  })

  it('withholds a foldedHash from text too short to match on', () => {
    // Same reasoning as the normalized layer: a folded greeting would match
    // every other folded greeting.
    expect(computeSignatureHashes('ок')?.foldedHash).toBe(null)
  })
})

describe('foldConfusables — glyph-soup obfuscation', () => {
  /**
   * Production 2026-07-31 12:34. Every letter that could be swapped, was —
   * IPA extensions, small capitals, a mathematical operator, Greek. Nothing
   * matched it: no signature, no vector neighbour, and the cheap model spent
   * 11.6 seconds tokenising it. The fold reached none of `ɯ ʍ ʙ ᴇ ҡ σ δ ∂`.
   */
  const obfuscated = 'Πρuглαɯαᴇʍ ʙ ҡσʍαн∂у! 18–35 лᴇτ Оτ 2500$ ∂σπσлнuτᴇльнαя δσнуснαя сuстᴇʍα'
  const plain = 'Приглашаем в команду! 18–35 лет От 2500$ дополнительная бонусная система'

  it('decodes the attack back onto its plain-letter twin', () => {
    expect(foldConfusables(normalizeLight(obfuscated)))
      .toBe(foldConfusables(normalizeLight(plain)))
  })

  it('gives the two the same signature hash', () => {
    expect(computeSignatureHashes(obfuscated)?.foldedHash)
      .toBe(computeSignatureHashes(plain)?.foldedHash)
  })

  it('и folds to u without colliding with п', () => {
    // The reason `и` had been excluded was that merging it with `n` would
    // collide with `п`. Folding it to `u` instead keeps them apart, which is
    // what makes the commonest substitution of all reachable.
    expect(foldConfusables('и')).toBe(foldConfusables('u'))
    expect(foldConfusables('и')).not.toBe(foldConfusables('п'))
    expect(foldConfusables('пиши')).not.toBe(foldConfusables('пипи'))
  })

  it('ordinary text of the two languages stays distinguishable', () => {
    const texts = [
      'Доброго дня, підкажіть будь ласка де відновити довідку',
      'Доброго дня, підкажіть будь ласка де отримати довідку',
      'Здравствуйте, подскажите пожалуйста где восстановить справку',
      'Шукаємо комплектувальника на склад у Львові, зарплата висока',
      'Приглашаем в команду! 18–35 лет От 2500$ дополнительная бонусная система'
    ]
    expect(new Set(texts.map((t) => foldConfusables(normalizeLight(t)))).size).toBe(texts.length)
  })
})
